{% set name = "cryptography_vectors" %}
{% set version = "2.0.3" %}
{% set sha256 = "beb831aa73663a224f4d7520483ed02da544533bb03b26ec07a5f9a0dd0941e1" %}

package:
  name: cryptography-vectors
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: Apache 2.0 or BSD 3-Clause
  #license_file: ??? TWO LICENSE FILES ???
  summary: Test vectors for the cryptography package.

extra:
  recipe-maintainers:
    - jakirkham
