{% set version = "38.0.1" %}

package:
  name: cryptography-vectors
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-{{ version }}.tar.gz
  sha256: 0431fd107c1fbad0377704a7051945b3b391169fddc4f6fa0bd4edc6b6e235dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - cryptography_vectors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyca/cryptography
  license: BSD-3-Clause OR Apache-2.0
  license_file:
    - LICENSE
    - LICENSE.BSD
    - LICENSE.APACHE
  summary: Test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/master/vectors
  doc_url: https://cryptography.io

extra:
  recipe-maintainers:
    - jakirkham
