{% set version = "2.2.1" %}
{% set sha256 = "be7cf2e4de057f2a5307d9600177014daefd58a96de9cb9f437c26753fd462fe" %}

package:
  name: cryptography-vectors
  version: {{ version }}

source:
  fn: cryptography_vectors-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cryptography_vectors/cryptography_vectors-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cryptography_vectors

about:
  home: https://github.com/pyca/cryptography
  license: Apache 2.0 or BSD 3-Clause
  #license_file: ??? TWO LICENSE FILES ???
  summary: Test vectors for the cryptography package.
  dev_url: https://github.com/pyca/cryptography/tree/master/vectors
  doc_url: https://cryptography.io

extra:
  recipe-maintainers:
    - jakirkham
