travis:
  secure:
    BINSTAR_TOKEN: pc+3fwgVVNxs/zKHIkort93V1Y/Gp9g0eHXh/p/IlKlN/DtWD/iT/9lu+VNGBGGHebpSAdHS67W6PsRZ/sPMGq6xtBQGgA4yxfpbcBW5qikFXV4YSXW2Ye24Awj4Ze0ZwT4Q2i169LsbbGLzvZNR8TyIE0y4a1T1qr+o0LQtkFzf4k6+nf9YPlxl75ARhxQpKuDgbskEhV+4ijUDlDfo/xUkjNkIrpRrsQqDmnmbwy5Kgyq/HtMwvHNOgPsx23XgtQ3UyebDH9awQEYl33aWSuYLIUZEpGMnEFfqnFU5Df15qfvaJfyBfKNhSTeox+wqqMYCbxMZgihgus2Nyh8CtwDZLy1SljwCFL5HPa0+OXZ+CWuzq4bw81g5wB07fKohKNN80ZXvfgH6ennSL3YCdd7ya+cb5OOHxrExdE2kFXVAskxIjUMaE8bCHarCvFDJXL9SMb1B+o0abQLh9QEd1zdL1XU7AdXj1JDCy6drnT5GDim6x9h+oI1P4Un886Aa4M8pDMGOpTm6Vykph9KGcvSq44ctHRLiYoDpaUHzyx2P8j1UhHZAyutSY5Cbm7B/xr5PVng/S12f1UNgP3bnKUp+vXbAISakrhuMFA7+yUPUl+m1HueYWgxzpF8IyYJts+qQMN35Cl0ClN79/69GxCVmaghj+MuGMj8i8tPgXzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
